spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thinhvo1811/20078241_VoQuocThinh_KTVTKPM_TH7_Spring_Cloud_Config_Server_File
          clone-on-start: true
        bootstrap: true
      enabled: true

  application:
    name: Config-Server